更新中文翻译（zh_cn）
Snownee/Jade pull request #339
Opened 2023-12-01 14:51 UTC by FlameFire26

- 去除不必要的翻译项（类似于`%s %s / %s`的文本）
- 根据`en_us.json`修改`"jade.llamaStrength": "力量：%d"`中的`%d`为`%s`
- 恕我不知`jade.theme`中的`top`和`create`项应如何翻译
- 去除中英文间的空格，除`"gui.jade.configuration": "Jade 配置"`和`"config.jade.plugin_jade": "Jade 核心"`之外
- 结尾带`extra_msg`的项未在游戏中发现显示位置，因此没有翻译

2023-12-01 16:30 UTC, Snownee requested changes

2023-12-01 16:30 UTC, Snownee commented on src/main/resources/assets/jade/lang/zh_cn.json
> -  "jade.potion": "%s（%s）",
请勿删除和英文内容一致的条目。另外中文括号与英文并不相同。

2023-12-01 16:30 UTC, Snownee commented on src/main/resources/assets/jade/lang/zh_cn.json
> +  "gui.jade.disabled_by_mods": "此选项被以下模组禁用:",
请使用中文标点。

2023-12-01 16:30 UTC, Snownee commented on src/main/resources/assets/jade/lang/zh_cn.json
> +  "gui.jade.search.hint": "搜索...",
请使用省略号“…”。

2023-12-01 16:30 UTC, Snownee commented on src/main/resources/assets/jade/lang/zh_cn.json
> +  "config.jade.edit_blocklist": "在文件中编辑方块列表...",
请使用省略号“…”。

2023-12-01 16:30 UTC, Snownee commented on src/main/resources/assets/jade/lang/zh_cn.json
> +  "key.jade.show_details_alternative": "显示细节 (切换)",
请使用中文标点。

2023-12-01 16:30 UTC, Snownee commented on src/main/resources/assets/jade/lang/zh_cn.json
> +  "config.jade.plugin_minecraft.entity_health.max_for_render": "显示红心最大值(大于则显示数字)",
请使用中文标点。

2023-12-01 16:30 UTC, Snownee commented on src/main/resources/assets/jade/lang/zh_cn.json
> +  "config.jade.plugin_minecraft.entity_armor.max_for_render": "显示盔甲的最大值(大于则显示数字)",
请使用中文标点。

2023-12-01 16:30 UTC, Snownee commented on src/main/resources/assets/jade/lang/zh_cn.json
> +  "config.jade.plugin_minecraft.harvest_tool.show_unbreakable": "显示 \"无法破坏\"",
请使用中文标点。

2023-12-01 16:30 UTC, Snownee commented on src/main/resources/assets/jade/lang/zh_cn.json
> +  "jade.collectingItems": "获取物品中..."
请使用省略号“…”。

2023-12-01 16:30 UTC, Snownee commented on src/main/resources/assets/jade/lang/zh_cn.json
> +  "jade.input_signal": "输入: %d",
请使用中文标点。

2023-12-01 16:30 UTC, Snownee commented on src/main/resources/assets/jade/lang/zh_cn.json
> +  "jade.zombieConversion.time": "转化时间: %s",
请使用中文标点。

2023-12-01 16:30 UTC, Snownee commented on src/main/resources/assets/jade/lang/zh_cn.json
> +  "config.jade.plugin_minecraft.energy_storage": "储能方块",
原文无“方块”的表述。

2023-12-02 05:34 UTC, qznfbnj commented
可以参考 https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/3591 和 https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/3960

2023-12-02 06:32 UTC, FlameFire26 commented
谢谢指正。
- 参考了#3960中`jade.theme`的翻译，不知`"jade.theme.jade.top": "One Probe（检测器）"`是否准确

2023-12-02 06:56 UTC, Snownee commented
翻译成{x}分，{x}秒比较好

2023-12-06 17:01 UTC, Snownee approved these changes

2023-12-06 17:01 UTC, merged

2023-12-06 17:07 UTC, qznfbnj commented
凋灵骷髅